### PR TITLE
Release as a universal wheel

### PR DESCRIPTION
**Pull request by adamchainz**
By releasing as a [Python wheel](http://pythonwheels.com/) as well as a source distribution, you can speed up end user’s installs. After merging this command, to release you just need to run `python setup.py clean sdist bdist_wheel upload`.

### CODE REVIEW

**Comment by danakatz** [comment]
Hi @adamchainz,

We agree that it would be nice to release as a universal wheel and will put this on our roadmap (along with a corresponding update to our internal release process). Thanks for the contribution! We'll post here when this is available.

**Comment by adamchainz** [comment]
This actually requires `setuptools` as per #75.

**Comment by danakatz** [comment]
We've decided not to move forward with this change due to the consequences of adding `setuptools` as a dependency (see #75).

Thanks for the PR!

**Comment by adamchainz** [comment]
See #76 for a way of not making `setuptools` a hard dependency.

**Pull request closed without merging**
