### PR TITLE
Some fixes to make dependencies & versioning work properly

### PR DESCRIPTION
**Pull request by fuhrysteve**
Also, adding a more comprehensive gitignore.

### CODE REVIEW

**Comment by alanhamlett** [comment]
@fuhrysteve what's the timeline on this getting merged and released? Checking for `None` with `==` is definitely a bug.

**Comment by fuhrysteve** [comment]
@alanhamlett I'm not a maintainer, so it's up to the folks at braintree I'm afraid! As far as I'm concerned, this is good to go.

**Comment by kexline4710** [comment]
@fuhrysteve

We took a look at the changes and your work on the `None` comparisons and `isinstance` assertions are very valuable; however, we prefer not to include so much in the `.gitignore` file.

To speed this along on our end, I've grabbed your last two commits (preserving your authorship) and extended it to encompass recent additions in the library. We've merged it internally and will be including it in an upcoming release. Thanks for your submission!

**Comment by alanhamlett** [comment]
While you're at it, #63 is a very small but valuable change.

Also, it seems you guys host the main code off GitHub and sync releases to this public repo?

**Comment by fuhrysteve** [comment]
Sounds great, thanks!

**Comment by kexline4710** [comment]
@fuhrysteve These changes were included in the [3.21.0 release](https://github.com/braintree/braintree_python/releases/tag/3.21.0). Thanks again for your work and for bringing this to our attention.

**Pull request closed without merging**
